spring:
  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:./data/testdb
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: name
    password: password
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always

myconfig:
  my-host: ssl://example.com
  my-port: 23894
  my-user: user
  my-pass: pass

api:
  clientId: "client123"
  url: "https://api.url.com"
  key: "api-access-key"
