spring:
  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:./data/testdb
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: name
    password: password
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always