name: Build Kotlin-Se

on:
  push:
    paths:
      - 'tutorials/kotlin-se/**'
      - '.github/workflows/kotlin-se.yml'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env: # define constant
      PROJECT_PREFIX: tutorials
      PROJECT_NAME: kotlin-se

    steps:
      - name: Export Global Var
        run: |
          echo "ALI_DOCKER_REGISTRY=${{ secrets.ALI_DOCKER_HUB_REGISTRY }}" >> $GITHUB_ENV
          echo "ALI_DOCKER_USERNAME=${{ secrets.ALI_DOCKER_REGISTRY_USERNAME }}" >> $GITHUB_ENV
          echo "ALI_DOCKER_PASSWORD=${{ secrets.ALI_DOCKER_REGISTRY_PASSWORD }}" >> $GITHUB_ENV
          echo "JASYPT_ENCRYPTOR_PASSWORD=${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}" >> $GITHUB_ENV
          echo "PROJECT_HOME=$PWD" >> $GITHUB_ENV
          echo "TAG=`echo \`date +%Y%m%d\`.${GITHUB_SHA} | cut -c1-16`" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          # architecture: x64

      - name: Cache Gradle Packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build Gradle Project
        run: |
          cd $PROJECT_HOME/$PROJECT_PREFIX/$PROJECT_NAME
          ./gradlew clean build -x test --console=plain

      # - name: Upload Gradle ec-product Artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: ec-product-1.0-SNAPSHOT.jar
      #     path: backend/project-ec/ec-product/build/libs

      # - name: Cache Maven packages
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.m2
      #     key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      #     restore-keys: ${{ runner.os }}-m2
      # - name: Build With Maven
      #   run: |
      #     cd backend/project-generator
      #     mvn clean package -DskipTests=true
